build/summary.md:
	cat \
	intro.md \
	internal_review/methodology.md \
	process_specification/data_collection.md \
	process_specification/data_reliability.md \
	internal_review/review_overview.md \
	internal_review/review_criteria.md \
	internal_review/additional_statuses.md \
	> ../build/'Red List Summary.md'