-- This script attempts to create postgres tables to import the iRecord data from SQLite into
-- CHECK YOUR DEFAULT DATE FORMAT BEFORE USING! This assumes that the default is set to DD/MM/YYYY format *NOT* MM/DD/YYYYY

CREATE TABLE bwars_redlist.all_irec (
	id	int,
	recordkey	text,
	external_key	text,
	source	text,
	rank	text,
	taxon	text,
	common_name	text,
	taxon_group	text,
	tax_kingdom	text,
	tax_order	text,
	tax_family	text,
	taxonversionkey	text,
	site_name	text,
	original_map_ref	text,
	latitude	real,
	longitude	real,
	projection_input	text,
	accuracy	real,
	output_map_ref	text,
	projection_output	text,
	biotope	text,
	vc_number	text,
	vice_county	text,
	date_interpreted	text,
	date_from	DATE,
	date_to	DATE,
	date_type	text,
	sample_method	text,
	recorder	text,
	determiner	text,
	recorder_certainty	text,
	sex	text,
	stage	text,
	count_of_sex_or_stage	text,
	zero_abundance	text,
	comment	text,
	sample_comment	text,
	images	text,
	input_on_date	TIMESTAMP,
	last_edited_on_date	TIMESTAMP,
	verification_status_1	text,
	verification_status_2	text,
	query	text,
	verifier	text,
	verified_on	TIMESTAMP,
	licence	text,
	automated_checks	text
);

CREATE TABLE bwars_redlist.processed (
	id	INTEGER NOT NULL UNIQUE,
	nik	INTEGER,
	gridref	TEXT,
	lower_date	TEXT,
	upper_date	TEXT,
	scriptlog	TEXT,
	pass	INTEGER NOT NULL
);